config/routes.rb
Rails.application.routes.draw do
  resources :teams, only: [:index]
  resources :clubs, only: [:index, :show] do
    resources :teams, only: [:index, :show, :edit, :update]
  end

  resources :subscriptions
  resources :single_payments
  resources :affiliate_discount_codes

  resources :unlocked_pyramid_modules, only: [:create, :destroy]
  resources :affiliations, only: [:destroy]

  devise_for :users, controllers: {
    registrations: 'devise_customizations/registrations',
    sessions: 'devise_customizations/sessions',
  }

  resources :users do
    member do
      get 'analytics_alias'
    end
  end

  post 'versions/:id/revert' => 'versions#revert', as: 'revert_version'
  namespace :admin do
    put 'sort' => 'application#sort'

    resources :pyramid_modules
    resources :unlocked_pyramid_modules
    resources :phases
    resources :workouts
    resources :exercises
    resources :exercise_workouts
    resources :clubs do
      member do
        get 'team_codes'
        post 'send_coach_invites'
      end
    end
    resources :teams
    resources :affiliations
    resources :enrollments
    resources :single_payments
    resources :affiliate_discount_codes
    resources :subscriptions
    resources :temp_teams
    resources :snippets

    resources :users do
      member do
        get 'impersonate'
        post 'invite'
      end

      collection do
        get 'stop_impersonating'
      end
    end

    root to: "users#index"
  end

  get '/pages/*id' => 'pages#show', as: :page, format: false
  get '/help' => 'pages#show', id: 'help'
  get '/unauthorized' => 'pages#show', id: 'unauthorized'

  get '/single_payments/:code', to: 'single_payments#index'
  post '/single_payments/verify_code', to: 'single_payments#verify_code', as: "verify_code"
  get '/purchase_confirmation/:slug', to: 'single_payments#purchase_confirmation'
  get '/thank-you', to: 'single_payments#thank_you'

  get '/replace-existing-to-complete' => 'single_payments#replace_existing_to_complete'
  get '/replace-existing-to-free' => 'single_payments#replace_existing_to_free'
  get '/generate-single-payments' => 'single_payments#generate_default_single_payments'

  get '/unlock-modules-for-club-players' => 'users#unlock_modules_for_club_players'
  get '/unlock-modules-for-club-players/:page' => 'users#unlock_modules_for_club_players'

  get '/clubs/:club_id/teams/:id/:page' => 'teams#show'
  get '/get-teams/:club_id', to: 'teams#get_teams'

  authenticated :user do
    root to: 'clubs#index', as: :authenticated_root
    # root to: 'pages#show', id: 'welcome', as: :authenticated_root
  end

  devise_scope :user do
    get 'sign-in',  to: 'devise/sessions#new'
    get 'sign-out', to: 'devise/sessions#destroy'

    # API-token creation aliases
    post 'api/v1/sign_in', to: 'devise_customizations/sessions#create'
    get 'api/v1/sign_out', to: 'devise_customizations/sessions#destroy'

  end

  root 'pages#show', id: 'welcome'

  namespace 'api' do
    namespace 'v1' do
      jsonapi_resources :pyramid_modules do
        jsonapi_resources :phases do
          jsonapi_resources :workouts do
            jsonapi_resources :exercises
          end
        end
      end
      jsonapi_resources :users do
        jsonapi_resources :teams
      end

      jsonapi_resources :confidence_ratings
      jsonapi_resources :archieved_user_payments
      jsonapi_resources :unlocked_pyramid_modules
      jsonapi_resources :phase_attempts
      jsonapi_resources :affiliations
      jsonapi_resources :teams
      jsonapi_resources :clubs
      jsonapi_resources :snippets

    end
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    include DefaultSort
    include AnalyticsTrack

    impersonates :user

    before_action :authenticate_user! # TODO: (2017-06-30) jon => backport to voyage
    before_action :authenticate_admin

    def destroy
      resource_to_destroy = requested_resource
      requested_resource.destroy
      flash[:notice] = translate_with_resource('destroy.success') + " #{undo_link(resource_to_destroy)}."
      redirect_to action: :index
    end

    private

    def authenticate_admin
      txt = 'You must be an admin to perform that action'
      redirect_to root_path, alert: txt unless current_user.admin?
    end

    def undo_link(resource)
      view_context.link_to('undo', revert_version_path(resource, model: resource.class.name), method: :post)
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    def records_per_page
      params[:per_page] || 25
    end
  end
end

app/controllers/application_controller.rb
# rubocop:disable Metrics/ClassLength, Metrics/MethodLength, Metrics/CyclomaticComplexity, Metrics/LineLength
class ApplicationController < ActionController::Base
  include AnalyticsTrack

  protect_from_forgery with: :exception, unless: -> { request.format.json? }
  check_authorization unless: :devise_or_pages_controller?
  impersonates :user

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, unless: -> { is_a?(HighVoltage::PagesController) }
  before_action :add_layout_name_to_gon
  before_action :detect_device_type
  before_action :set_clubs, unless: -> { request.format.json? }
  before_action :check_subscription, unless: -> { request.format.json? || devise_or_pages_controller? }

  respond_to :json, :html, if: :devise_controller? # for devise reset password

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json do
        render json: {
          errors: [
            title: exception.message,
            status: '403',
          ],
        }, status: :forbidden
      end

      format.html { redirect_to '/unauthorized', alert: exception.message }
    end
  end

  protected

  def set_clubs
    @clubs = [] and return unless current_user

    @clubs ||=
      if current_user.admin?
        Club.all.order(:name)
      else
        affiliated_club_ids = current_user.clubs_coached.map(&:id) # coach
        clubs_administered_ids = current_user.clubs_administered.map(&:id)
        ids = (affiliated_club_ids + clubs_administered_ids).uniq
        Club.where(id: ids).order(:name)
      end
  end

  def check_subscription
    return if @clubs.present? # club admin or coach

    # Player
    if current_user && !request.path.match?('analytics_alias')
      if current_user.active_subscription?
        redirect_to edit_user_registration_path and return
      else
        if current_user.team_player?
          redirect_to edit_user_registration_path and return
        else
          redirect_to single_payments_path and return
        end
      end
    end
  end

  def devise_or_pages_controller?
    devise_controller? == true || is_a?(HighVoltage::PagesController)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up,
      keys: %i[
        first_name
        last_name
        email
        password
        password_confirmation
        remember_me
      ],
    )

    devise_parameter_sanitizer.permit(
      :sign_in,
      keys: %i[
        login email password remember_me
      ],
    )

    devise_parameter_sanitizer.permit(
      :account_update,
      keys: %i[
        first_name
        last_name
        email
        avatar
        password
        password_confirmation
        current_password
      ],
    )
  end

  def add_layout_name_to_gon
    gon.layout =
      case devise_controller?
      when true
        'devise'
      else
        'application'
      end
  end

  def detect_device_type
    request.variant =
      case request.user_agent
      when /iPad/i
        :tablet
      when /iPhone/i
        :phone
      when /Android/i && /mobile/i
        :phone
      when /Android/i
        :tablet
      when /Windows Phone/i
        :phone
      end
  end

  def handle_unverified_request
    flash[:error] = 'You have been signed out of your current session'
    redirect_to "/"
  end
end

app/helpers/admin/application_helper.rb
module Admin
  module ApplicationHelper
    include AdministrateResourcesHelper

    def sanitized_order_params
      resources =
        Administrate::Namespace.new(:admin).
          resources.
          map(&:resource).
          map(&:to_sym) + [:players, :coaches, :available_pyramid_modules]

      params.permit(
        *resources,
        :search,
        :id,
        :order,
        :page,
        :per_page,
        :direction,
      )
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # rubocop:disable Metrics/MethodLength
  def errors_for(object)
    return if object.errors.blank?

    content_tag(:div, class: 'error_notification') do
      concat(
        content_tag(:div, class: 'panel-heading') do
          concat(
            content_tag(:h4, class: 'panel-title') do
              concat("#{pluralize(object.errors.count, 'error')} prohibited this #{object.class.name.downcase} from being saved:") # rubocop:disable Metrics/LineLength
            end,
          )
        end,
      )
      concat(
        content_tag(:div, class: 'panel-body') do
          concat(
            content_tag(:ul) do
              object.errors.full_messages.each do |msg|
                concat(content_tag(:li, msg))
              end
            end,
          )
        end,
      )
    end
  end
  # rubocop:enable Metrics/MethodLength
end

app/views/admin/application/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<% if resources.first.respond_to?(:has_many_through_sort_scope) %>
  <% sort_model = resources.first.has_many_through_sort_scope %>
<% else %>
  <% sort_model = resources.first.class.name %>
<% end %>

<table
  class='table table-responsive'
  aria-labelledby="<%= table_title %>"
  data-sortable-parent-model-id="<%= params[:id] %>"
  data-sortable-model="<%= sort_model %>"
  data-resource-model="<%= resources.first.class.name %>"
  data-sortable-update-endpoint="/admin/sort"
  >
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <% custom_attr_name = attr_type.try(:options).try(:fetch, :order, attr_name) || attr_name %>

        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(custom_attr_name) %>"
        scope="col"
        role="columnheader"
        aria-sort="<%= sort_order(collection_presenter.ordered_html_class(custom_attr_name)) %>">
          <% link_text = t(
            "helpers.label.#{resource_name}.#{attr_name}",
            default: attr_name.to_s,
          ).titleize %>
          <% if attr_type.try(:options).try(:fetch, :sortable, true) == false %>
            <%= link_text %>
          <% else %>
            <%= link_to(sanitized_order_params.merge(collection_presenter.order_params_for(custom_attr_name || attr_name))) do %>
              <%= link_text %>
              <% if collection_presenter.ordered_by?(custom_attr_name) %>
                <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(custom_attr_name) %>">
                  <svg aria-hidden="true">
                    <use xlink:href="#icon-up-caret" />
                  </svg>
                </span>
              <% end %>
            <% end %>
          <% end %>
        </th>
      <% end %>

      <% # override for the hmt join model, so we can display the position without edit or destroy %>
      <% unless resources.first.class.name == 'ExerciseWorkout' %>
        <% [valid_action?(:edit, collection_presenter.resource_name),
            valid_action?(:destroy, collection_presenter.resource_name)].count(true).times do %>
          <th scope="col"></th>
        <% end %>
      <% end %>
    </tr>
  </thead>

  <tbody id="<%= 'table_body_id' unless controller.controller_name == 'exercises' %>">
    <% resources.each do |resource| %>
      <tr class="js-table-row"
          tabindex="0"
          data-table-row-id="<%= resource.id %>"
          <% if valid_action? :show, collection_presenter.resource_name %>
            <%= %(role=link data-url=#{polymorphic_path([namespace, resource])}) %>
          <% end %>
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <a href="<%= polymorphic_path([namespace, resource]) -%>"
               class="action-show"
               >
              <%= render_field attribute %>
            </a>
          </td>
        <% end %>

        <% # override for the hmt join model, so we can display the position without edit or destroy %>
        <% unless resource.class.name == 'ExerciseWorkout' %>
          <% if valid_action? :edit, collection_presenter.resource_name %>
            <td><%= link_to(
              t("administrate.actions.edit"),
              [:edit, namespace, resource],
              class: "action-edit",
            ) %></td>
          <% end %>

          <% if valid_action? :destroy, collection_presenter.resource_name %>
            <td><%= link_to(
              t("administrate.actions.destroy"),
              [namespace, resource],
              class: "text-color-red",
              method: :delete,
              data: { confirm: t("administrate.actions.confirm") }
            ) %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/application/_flashes.html.erb
<%#
# Flash Partial

This partial renders flash messages on every page.

## Relevant Helpers:

- `flash`:
  Returns a hash,
  where the keys are the type of flash (alert, error, notice, etc)
  and the values are the message to be displayed.
%>

<% if flash.any? %>
  <div class="flashes">
    <% flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>"><%= value.html_safe %></div>
    <% end -%>
  </div>
<% end %>

app/views/admin/application/_navigation.html.erb
<%#
# Navigation

This partial is used to display the navigation in Administrate.
By default, the navigation contains navigation links
for all resources in the admin dashboard,
as defined by the routes in the `admin/` namespace
%>

<nav class="navigation" role="navigation">
  <% resources_for_sidebar_nav.each do |resource| %>
    <%= link_to(
      ( display_resource_name(resource) == "Affiliate Discount Codes" ? "Affiliate/Discount Codes" : display_resource_name(resource) ),
      [namespace, resource.path],
      class: "navigation__link navigation__link--#{nav_link_state(resource)}"
    ) %>
  <% end %>

  <div style='width: 130px; background: #c0c0c0; height: 1px; margin: 25px 0 20px 0;'>&nbsp;</div>

  <%= link_to 'Non-Admin-View', root_path, class: 'navigation__link' %>
  <%= link_to 'Sign Out', sign_out_path, class: 'navigation__link' %>
</nav>

app/views/admin/application/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { "#{t("administrate.actions.show")} #{page.page_title}" } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      "#{t("administrate.actions.edit")} #{page.page_title}",
      [:edit, namespace, page.resource],
      class: "button",
    ) if valid_action? :edit %>
  </div>
</header>

<section class="main-content__body" data-parent-model-name="<%= page.resource.class.name %>">
  <dl>
    <% page.attributes.each do |attribute| %>
      <dt class="attribute-label" id="<%= attribute.name %>">
      <%= t(
        "helpers.label.#{resource_name}.#{attribute.name}",
        default: attribute.name.titleize,
      ) %>
      </dt>

      <dd class="attribute-data attribute-data--<%=attribute.html_class%>">
        <%= render_field attribute %>
      </dd>
    <% end %>
  </dl>
</section>