config/routes.rb
Rails.application.routes.draw do
  resources :teams, only: [:index]
  resources :clubs, only: [:index, :show] do
    resources :teams, only: [:index, :show, :edit, :update]
  end

  resources :subscriptions
  resources :single_payments
  resources :affiliate_discount_codes

  resources :unlocked_pyramid_modules, only: [:create, :destroy]
  resources :affiliations, only: [:destroy]

  devise_for :users, controllers: {
    registrations: 'devise_customizations/registrations',
    sessions: 'devise_customizations/sessions',
  }

  resources :users do
    member do
      get 'analytics_alias'
    end
  end

  post 'versions/:id/revert' => 'versions#revert', as: 'revert_version'
  namespace :admin do
    put 'sort' => 'application#sort'

    resources :pyramid_modules
    resources :unlocked_pyramid_modules
    resources :phases
    resources :workouts
    resources :exercises
    resources :exercise_workouts
    resources :clubs do
      member do
        get 'team_codes'
        post 'send_coach_invites'
      end
    end
    resources :teams
    resources :affiliations
    resources :enrollments
    resources :single_payments
    resources :affiliate_discount_codes
    resources :subscriptions
    resources :temp_teams
    resources :snippets

    resources :users do
      member do
        get 'impersonate'
        post 'invite'
      end

      collection do
        get 'stop_impersonating'
      end
    end

    root to: "users#index"
  end

  get '/pages/*id' => 'pages#show', as: :page, format: false
  get '/help' => 'pages#show', id: 'help'
  get '/unauthorized' => 'pages#show', id: 'unauthorized'

  get '/single_payments/:code', to: 'single_payments#index'
  post '/single_payments/verify_code', to: 'single_payments#verify_code', as: "verify_code"
  get '/purchase_confirmation/:slug', to: 'single_payments#purchase_confirmation'
  get '/thank-you', to: 'single_payments#thank_you'

  get '/replace-existing-to-complete' => 'single_payments#replace_existing_to_complete'
  get '/replace-existing-to-free' => 'single_payments#replace_existing_to_free'
  get '/generate-single-payments' => 'single_payments#generate_default_single_payments'

  get '/unlock-modules-for-club-players' => 'users#unlock_modules_for_club_players'
  get '/unlock-modules-for-club-players/:page' => 'users#unlock_modules_for_club_players'

  get '/clubs/:club_id/teams/:id/:page' => 'teams#show'
  get '/get-teams/:club_id', to: 'teams#get_teams'

  authenticated :user do
    root to: 'clubs#index', as: :authenticated_root
    # root to: 'pages#show', id: 'welcome', as: :authenticated_root
  end

  devise_scope :user do
    get 'sign-in',  to: 'devise/sessions#new'
    get 'sign-out', to: 'devise/sessions#destroy'

    # API-token creation aliases
    post 'api/v1/sign_in', to: 'devise_customizations/sessions#create'
    get 'api/v1/sign_out', to: 'devise_customizations/sessions#destroy'

  end

  root 'pages#show', id: 'welcome'

  namespace 'api' do
    namespace 'v1' do
      jsonapi_resources :pyramid_modules do
        jsonapi_resources :phases do
          jsonapi_resources :workouts do
            jsonapi_resources :exercises
          end
        end
      end
      jsonapi_resources :users do
        jsonapi_resources :teams
      end

      jsonapi_resources :confidence_ratings
      jsonapi_resources :archieved_user_payments
      jsonapi_resources :unlocked_pyramid_modules
      jsonapi_resources :phase_attempts
      jsonapi_resources :affiliations
      jsonapi_resources :teams
      jsonapi_resources :clubs
      jsonapi_resources :snippets

    end
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  include Stripe::Callbacks

  belongs_to :club, optional: true, inverse_of: :subscriptions
  belongs_to :user, optional: true, inverse_of: :subscription

  has_many :enrollments, dependent: :destroy
  has_many :teams, through: :enrollments

  has_many :players, through: :teams

  scope :current, (lambda {
    where('subscriptions.end_date >= ?', Time.current.to_date)
    .where('subscriptions.start_date <= ?', Time.current.to_date)
    .order(end_date: :desc)
  })

  validates :start_date, :end_date, :price, presence: true
  validates :start_date, :end_date, overlap: { scope: 'club_id' }, if: proc { |a| a.club_id.present? }, on: :update
  validates :start_date, :end_date, overlap: { scope: 'user_id' }, if: proc { |a| a.user_id.present? }, on: :update

  validates :start_date, inclusion: {
    in: ->(_subscription) { Time.zone.today..Time.zone.today + 50.years },
    message: 'must be today or further in the future',
  }, on: :create

  validate :end_date_is_after_start_date

  delegate :fee, to: :club, prefix: true

  def current?
    end_date >= Time.current.to_date && start_date <= Time.current.to_date
  end

  def extend_until(new_date, metadata={})
    if created_at.to_date < 1.day.ago
      # we didn't just create the subscription
      update(end_date: new_date)
    end

    update(metadata: metadata)
  end

  private

  after_charge_succeeded! do |charge|
    logger.info charge.inspect
    stripe_customer_id = charge.customer
    stripe_invoice_id = charge.invoice

    if !stripe_customer_id.nil? && !stripe_invoice_id.nil?
      stripe_invoice = Stripe::Invoice.retrieve(stripe_invoice_id)

      if !stripe_invoice.lines.data.first.plan.nil?
        stripe_plan_id = stripe_invoice.lines.data.first.plan.id

        new_end_date =
          case stripe_plan_id
          when /monthly.*/
            1.month.from_now
          when /annually.*/
            1.year.from_now
          end

        user = User.find_by(stripe_customer_id: stripe_customer_id)

        if !user.id.nil?
          subscription = Subscription.find_by(user_id: user.id)

          # NOTE: (2018-07-08) jon => assumes "Central Time (US & Canada)" remains set
          dst_or_not = Time.current.dst? ? 'CDT' : 'CST'
          date_and_time_with_period =
            "#{Time.current.strftime('%m/%d/%Y - %-l:%M %p')} #{dst_or_not}"

          metadata = {
            date_and_time_with_period => { stripe_invoice_id: stripe_invoice_id }
          }

          subscription.extend_until(new_end_date, metadata)
        end
      end
    end
  end

  def end_date_is_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date <= start_date
      errors.add(:end_date, 'must be at least 1 day after the start date')
    end
  end
end

# == Schema Information
#
# Table name: subscriptions
#
#  club_id    :integer
#  created_at :datetime         not null
#  end_date   :date
#  id         :integer          not null, primary key
#  metadata   :json
#  price      :decimal(, )
#  start_date :date
#  updated_at :datetime         not null
#  user_id    :integer
#
# Indexes
#
#  index_subscriptions_on_club_id  (club_id)
#  index_subscriptions_on_user_id  (user_id)
#

app/controllers/admin/subscriptions_controller.rb
module Admin
  class SubscriptionsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Subscription.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Subscription.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  skip_authorization_check

  #skip_before_action :check_subscription

  def index
  end

  def create
    plan_type = params[:plan_type]

    unless plan_type == 'forever'
      plan = "Stripe::Plans::#{plan_type.upcase}".constantize
      price = plan.amount / 100 rescue 0
    end

    if plan_type.match?('monthly')
      end_date = 1.month.from_now
    elsif plan_type.match?('annually')
      end_date = 1.year.from_now
    elsif plan_type.match?('forever')
      end_date = 100.years.from_now
      price = 250 # override price to fixed amount that Verek and Scott wanted
    end

    Subscription.create!(
      user: current_user,
      start_date: Time.zone.today,
      end_date: end_date,
      price: price,
    )

    customer =
      begin
        Stripe::Customer.retrieve(current_user.stripe_customer_id)
      rescue Stripe::InvalidRequestError
        # TODO: (2018-01-13) jon => log the Customer retrieve failure if current_user.stripe_customer_id.present?
        Stripe::Customer.create(
          description: current_user.full_name,
          email: current_user.email,
          source: params[:stripeToken], # obtained with Stripe.js
        )
      end

    current_user.update_column(:stripe_customer_id, customer.id)

    raise "Problem creating Stripe customer for #{current_user.email}." if customer.blank? || current_user.stripe_customer_id.blank?
    # TODO: (2018-01-13) jon => Log this

    if plan_type == 'forever'
      Stripe::Charge.create(
        amount: price * 100,
        currency: 'usd',
        customer: customer.id,
        description: "Charge for #{current_user.email}"
      )

      flash[:notice] = 'Lifetime subscription successfully created. Your subscription will never expire.'
    else
      Stripe::Subscription.create(
        customer: customer.id,
        items: [
          {
            plan: plan_type,
          },
        ],
      )

      flash[:notice] = "Subscription successfully created."
    end

    redirect_to edit_user_registration_path
  rescue => e
    flash[:error] = "Sorry, something went wrong. Please forward these error details to info@risefutbol.com.<br><br>Error: #{e}".html_safe
    redirect_to '/help'
  end
end

app/views/subscriptions/_plan_button.html.slim
- # TODO: (2018-01-13) jon => wrap the plan price finders in an object. Rescues are not good for control flow
- plan = "Stripe::Plans::#{plan_type.upcase}".constantize rescue nil
- price = plan.amount / 100 rescue 250
ruby:
  case plan_type
  when 'monthly'
    plan_checkout_title = 'Rise Monthly Subscription'
    plan_frequency = 'per month'
    price = 30
  when 'monthly_with_coaching'
    plan_checkout_title = 'Rise Monthly w/ Coaching'
    plan_frequency = 'per month'
  when 'annually'
    plan_checkout_title = 'Rise Annual Subscription'
    plan_frequency = 'per year'
  when 'annually_with_coaching'
    plan_checkout_title = 'Rise Annual w/ Coaching'
    plan_frequency = 'per year'
  when 'forever'
    plan_checkout_title = 'Own It Forever'
    plan_frequency = 'Own It Forever'
  end

= form_tag subscriptions_path do
  script{
    src="https://checkout.stripe.com/checkout.js"
    class="stripe-button"
    data-key="#{ENV['STRIPE_PUBLISHABLE_KEY']}"
    data-locale="auto"
    data-label="$#{price} #{plan_frequency}"
    data-name="#{plan_checkout_title}"
    data-description="$#{price}"
    data-email="#{current_user.email}"
  }
  = hidden_field_tag 'plan_type', plan_type

sass:
  button.stripe-button-el
    background-color: white
    background-image: none
    border: none
    border-radius: none
    box-shadow: none
    height: 32px
    width: 215px

  button.stripe-button-el span
    background-color: #3adb76
    background-image: none

app/views/subscriptions/index.html.slim
header.main-content__header[role='banner']
  .row.columns
    .group.small-12.medium-8.left
      | Choose Subscription

.row.columns
  br
  h3 Please choose a subscription level before continuing.

  div(class='#{params[:plan_type] == 'monthly' ? 'highlight' : ''}')
    .left
      = render 'plan_button', { plan_type: 'monthly' }
    p &nbsp; Monthly Subscription

  div(class='#{params[:plan_type] == 'monthly_with_coaching' ? 'highlight' : ''}')
    .left
      = render 'plan_button', { plan_type: 'monthly_with_coaching' }
    p &nbsp; Monthly Subscription with Personal Coaching

  div(class='#{params[:plan_type] == 'annually' ? 'highlight' : ''}')
    .left
      = render 'plan_button', { plan_type: 'annually' }
    p &nbsp; Annual Subscription

  div(class='#{params[:plan_type] == 'annually_with_coaching' ? 'highlight' : ''}')
    .left
      = render 'plan_button', { plan_type: 'annually_with_coaching' }
    p &nbsp; Annual Subscription with Personal Coaching

  div(class='#{params[:plan_type] == 'forever' ? 'highlight' : ''}')
    .left
      = render 'plan_button', { plan_type: 'forever' }
    p &nbsp; Own The Whole Thing

sass:
  p
    padding-top: 4px
  .left
    margin-left: 20px
  .highlight
    padding: 25px 20px 15px 20px
    margin: 20px 0 20px 0
    border: 2px solid #3adb76
    .left
      margin-left: 0