config/routes.rb
Rails.application.routes.draw do
  resources :teams, only: [:index]
  resources :clubs, only: [:index, :show] do
    resources :teams, only: [:index, :show, :edit, :update]
  end

  resources :subscriptions
  resources :single_payments
  resources :affiliate_discount_codes

  resources :unlocked_pyramid_modules, only: [:create, :destroy]
  resources :affiliations, only: [:destroy]

  devise_for :users, controllers: {
    registrations: 'devise_customizations/registrations',
    sessions: 'devise_customizations/sessions',
  }

  resources :users do
    member do
      get 'analytics_alias'
    end
  end

  post 'versions/:id/revert' => 'versions#revert', as: 'revert_version'
  namespace :admin do
    put 'sort' => 'application#sort'

    resources :pyramid_modules
    resources :unlocked_pyramid_modules
    resources :phases
    resources :workouts
    resources :exercises
    resources :exercise_workouts
    resources :clubs do
      member do
        get 'team_codes'
        post 'send_coach_invites'
      end
    end
    resources :teams
    resources :affiliations
    resources :enrollments
    resources :single_payments
    resources :affiliate_discount_codes
    resources :subscriptions
    resources :temp_teams
    resources :snippets

    resources :users do
      member do
        get 'impersonate'
        post 'invite'
      end

      collection do
        get 'stop_impersonating'
      end
    end

    root to: "users#index"
  end

  get '/pages/*id' => 'pages#show', as: :page, format: false
  get '/help' => 'pages#show', id: 'help'
  get '/unauthorized' => 'pages#show', id: 'unauthorized'

  get '/single_payments/:code', to: 'single_payments#index'
  post '/single_payments/verify_code', to: 'single_payments#verify_code', as: "verify_code"
  get '/purchase_confirmation/:slug', to: 'single_payments#purchase_confirmation'
  get '/thank-you', to: 'single_payments#thank_you'

  get '/replace-existing-to-complete' => 'single_payments#replace_existing_to_complete'
  get '/replace-existing-to-free' => 'single_payments#replace_existing_to_free'
  get '/generate-single-payments' => 'single_payments#generate_default_single_payments'

  get '/unlock-modules-for-club-players' => 'users#unlock_modules_for_club_players'
  get '/unlock-modules-for-club-players/:page' => 'users#unlock_modules_for_club_players'

  get '/clubs/:club_id/teams/:id/:page' => 'teams#show'
  get '/get-teams/:club_id', to: 'teams#get_teams'

  authenticated :user do
    root to: 'clubs#index', as: :authenticated_root
    # root to: 'pages#show', id: 'welcome', as: :authenticated_root
  end

  devise_scope :user do
    get 'sign-in',  to: 'devise/sessions#new'
    get 'sign-out', to: 'devise/sessions#destroy'

    # API-token creation aliases
    post 'api/v1/sign_in', to: 'devise_customizations/sessions#create'
    get 'api/v1/sign_out', to: 'devise_customizations/sessions#destroy'

  end

  root 'pages#show', id: 'welcome'

  namespace 'api' do
    namespace 'v1' do
      jsonapi_resources :pyramid_modules do
        jsonapi_resources :phases do
          jsonapi_resources :workouts do
            jsonapi_resources :exercises
          end
        end
      end
      jsonapi_resources :users do
        jsonapi_resources :teams
      end

      jsonapi_resources :confidence_ratings
      jsonapi_resources :archieved_user_payments
      jsonapi_resources :unlocked_pyramid_modules
      jsonapi_resources :phase_attempts
      jsonapi_resources :affiliations
      jsonapi_resources :teams
      jsonapi_resources :clubs
      jsonapi_resources :snippets

    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    skip_before_action :authenticate_admin, only: [:stop_impersonating]

    before_action :default_params

    def create
      @user = User.invite!(resource_params) do |u|
        u.skip_invitation = true
      end

      flash[:notice] = 'User successfully created, but not yet invited.'
      redirect_to admin_users_path
    end

    def update
      params[:user].delete(:password) if params[:user][:password].blank?
      params[:user].delete(:password_confirmation) if params[:user][:password_confirmation].blank?
      super
    end

    def impersonate
      user = User.find(params[:id])
      track_impersonation(user, 'Start')
      impersonate_user(user)
      redirect_to root_path
    end

    def stop_impersonating
      track_impersonation(current_user, 'Stop')
      stop_impersonating_user
      redirect_to admin_users_path
    end

    def invite
      user = User.find(params[:id])
      user.invite!(current_user)
      redirect_to admin_users_path
    end

    private

    def resource_params
      params.require(resource_name).permit(
        *dashboard.permitted_attributes,
        team_ids: [],
        roles: [],
      )
    end

    def track_impersonation(user, status)
      analytics_track(
        true_user,
        "Impersonation #{status}",
        impersonated_user_id: user.id,
        impersonated_user_email: user.email,
        impersonated_by_email: true_user.email,
      )
    end

    def default_params
      params[:order] ||= 'created_at'
      params[:direction] ||= 'desc'
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < BaseApiController
      include RenderJsonUserWithToken

      load_and_authorize_resource(except: :create)
      skip_authorization_check(only: :create)
      skip_before_action :authenticate_user!, only: :create
      skip_before_action :verify_authenticity_token, only: [:create, :update]

      def index
        jsonapi_render json: User.all
      end

      def show
        analytics_track(current_user, 'Show User', { user_db_id: @user.id, showing_self: current_user.id == @user.id })
        jsonapi_render json: @user
      end

      def create
        free_payment = SinglePayment.where(price: 0).first
        @user = User.new(user_params)
        @user.roles << :player
        @user.single_payment_id = free_payment.id
        if @user.save

          free_payment.pyramid_modules.each do |pyramid_module|
            if UnlockedPyramidModule.where(pyramid_module_id: pyramid_module.id).where(user_id: @user.id).empty? 
              UnlockedPyramidModule.create(pyramid_module_id: pyramid_module.id, user_id: @user.id, has_restriction: 1)
            else
              UnlockedPyramidModule.where(pyramid_module_id: pyramid_module.id).where(user_id: @user.id).update(has_restriction: 1)
            end
          end

          @user.analytics_identify(traits: { sign_up_source: 'App' })

          # On successful creation, generate token and return in response
          render_json_user_with_token(@user, return_user: false)
        else
          jsonapi_render_errors json: @user, status: :unprocessable_entity
        end
      end

      def update
        if @user.update_attributes(user_params)
          jsonapi_render json: @user, status: :ok
        else
          jsonapi_render_errors json: @user, status: :unprocessable_entity
        end
      end

      def destroy
        @user.destroy
        head :no_content
      end

      private

      def user_params
        resource_params
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_resource
  authorize_resource except: [:analytics_alias]
  skip_authorization_check only: [:analytics_alias]

  def analytics_alias
    # view file has JS that will identify the anonymous user through segment
    # after registration via "after devise registration path"
  end

	def unlock_modules_for_club_players
	  render_text = "test"
	  unlock_pyramid_module_values = Array.new
	  today = Date.today

	  page = params[:page].nil? ? 0 : params[:page].to_i
	  limit = 150
	  offset = page * limit

		render_text = ""

	  pyramid_modules = PyramidModule.select("id,name").where(id: [3,5,7,8,9,10,11,12,13,15,16,17]).order(:id)

	  affiliations = Affiliation.joins(:user).select("affiliations.id, affiliations.user_id, users.email as user_email").where(deleted_at: nil).offset(offset).limit(limit)
	  aux = 0
	  affiliations.each do |affiliation|
	  	aux = 0
	  	pyramid_modules.each do |pyramid_module|
	  		if UnlockedPyramidModule.where(pyramid_module_id: pyramid_module.id).where(user_id: affiliation.user_id).empty? 
          unlock_pyramid_module_values << "(#{affiliation.user_id},#{pyramid_module.id},'{}','2020-03-25 01:23:45','2020-03-25 01:23:45')"
          aux = 1
        end
	  	end
      if (aux == 1)
	  		render_text += "#{affiliation.user_email} \n"
	  	end
	  end


    if (unlock_pyramid_module_values.count > 0)
      unlock_complete_training_modules_sql = "INSERT INTO unlocked_pyramid_modules (user_id, pyramid_module_id, completed_phases, created_at, updated_at) VALUES #{unlock_pyramid_module_values.join(',')};"
      ActiveRecord::Base.connection.execute(unlock_complete_training_modules_sql)
    end

	  render plain: render_text
	end
end

app/views/admin/users/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<% if resources.first.respond_to?(:has_many_through_sort_scope) %>
  <% sort_model = resources.first.has_many_through_sort_scope %>
<% else %>
  <% sort_model = resources.first.class.name %>
<% end %>

<table
  class='table table-responsive'
  aria-labelledby="<%= table_title %>"
  data-sortable-parent-model-id="<%= params[:id] %>"
  data-sortable-model="<%= sort_model %>"
  data-resource-model="<%= resources.first.class.name %>"
  data-sortable-update-endpoint="/admin/sort"
  >
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <% custom_attr_name = attr_type.try(:options).try(:fetch, :order, attr_name) || attr_name %>

        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(custom_attr_name) %>"
        scope="col"
        role="columnheader"
        aria-sort="<%= sort_order(collection_presenter.ordered_html_class(custom_attr_name)) %>">
          <% link_text = t(
            "helpers.label.#{resource_name}.#{attr_name}",
            default: attr_name.to_s,
          ).titleize %>
          <% if attr_type.try(:options).try(:fetch, :sortable, true) == false %>
            <%= link_text %>
          <% else %>
            <%= link_to(sanitized_order_params.merge(collection_presenter.order_params_for(custom_attr_name || attr_name))) do %>
              <%= link_text %>
              <% if collection_presenter.ordered_by?(custom_attr_name) %>
                <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(custom_attr_name) %>">
                  <svg aria-hidden="true">
                    <use xlink:href="#icon-up-caret" />
                  </svg>
                </span>
              <% end %>
            <% end %>
          <% end %>
        </th>
      <% end %>

      <% if resources.first.is_a?(User) %>
        <th scope="col">Impersonate</th>
      <% end %>

      <% # override for the hmt join model, so we can display the position without edit or destroy %>
      <% unless resources.first.class.name == 'ExerciseWorkout' %>
        <% [valid_action?(:edit, collection_presenter.resource_name),
            valid_action?(:destroy, collection_presenter.resource_name)].count(true).times do %>
          <th scope="col"></th>
        <% end %>
      <% end %>
    </tr>
  </thead>

  <tbody id="<%= 'table_body_id' unless controller.controller_name == 'exercises' %>">
    <% resources.each do |resource| %>
      <tr class="js-table-row"
          tabindex="0"
          data-table-row-id="<%= resource.id %>"
          <% if valid_action? :show, collection_presenter.resource_name %>
            <%= %(role=link data-url=#{polymorphic_path([namespace, resource])}) %>
          <% end %>
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <a href="<%= polymorphic_path([namespace, resource]) -%>"
               class="action-show"
               >
              <%= render_field attribute %>
            </a>
          </td>
        <% end %>

        <% if resource.is_a?(User) %>
          <td class="cell-data cell-data--string">
            <a href="<%= impersonate_admin_user_path(resource) -%>" class="action-show" >
              Go
            </a>
          </td>
        <% end %>

        <% # override for the hmt join model, so we can display the position without edit or destroy %>
        <% unless resource.class.name == 'ExerciseWorkout' %>
          <% if valid_action? :edit, collection_presenter.resource_name %>
            <td><%= link_to(
              t("administrate.actions.edit"),
              [:edit, namespace, resource],
              class: "action-edit",
            ) %></td>
          <% end %>

          <% if valid_action? :destroy, collection_presenter.resource_name %>
            <td><%= link_to(
              t("administrate.actions.destroy"),
              [namespace, resource],
              class: "text-color-red",
              method: :delete,
              data: { confirm: t("administrate.actions.confirm") }
            ) %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/_form.html.erb
<%#
# Form Partial

This partial is rendered on a resource's `new` and `edit` pages,
and renders all form fields for a resource's editable attributes.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<%= form_for([namespace, page.resource], html: { class: "form" }) do |f| %>
  <% if page.resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(page.resource.errors.count, "error") %>
        prohibited this <%= page.resource_name %> from being saved:
      </h2>

      <ul>
        <% page.resource.errors.full_messages.each do |message| %>
          <li class="flash-error"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% page.attributes.each do |attribute| -%>
    <div class="field-unit field-unit--<%= attribute.html_class %>">
      <%= render_field attribute, f: f %>
    </div>
  <% end -%>

  <%= render 'admin/users/role_edit', { f: f, user: page.resource, roles: User::ROLES } %>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/_password_fields.html.slim
- if user.new_record?
  .field-unit
    .field-unit__label
      = f.label :password, 'Password'

    .field-unit__field
      = f.password_field :password

  .field-unit
    .field-unit__label
      = f.label :password, 'Password Confirmation'

    .field-unit__field
      = f.password_field :password_confirmation

app/views/admin/users/_role_edit.html.erb
<%# TODO: (2017-06-11) jon => bring this back to voyage %>
<div class="field-unit">
  <div class='field-unit__label'>
    <%= label_tag 'roles', 'Roles' %>
  </div>

  <div class='field-unit__field'>
    <% for role in roles %>
      <div class=''>
        <%= check_box_tag "user[roles]", role, user.roles.include?(role), { name: 'user[roles][]', style: 'margin: 0px;' } %>
        <%= label_tag "user_roles_#{role}", role.to_s.humanize, style: 'position: relative; top: -5px;' %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/edit.html.erb
<%#
# Edit

This view is the template for the edit page.

It displays a header, and renders the `_form` partial to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) { "#{t("administrate.actions.edit")} #{page.page_title}" } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      "#{t("administrate.actions.show")} #{page.page_title}",
      [namespace, page.resource],
      class: "button",
    ) if valid_action? :show %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

app/views/admin/users/edit.html.slim
h2 Editing User

= simple_form_for(@user, url: admin_user_path(@user), html: { method: :put }) do |f|
  = errors_for(@user)
  .form-inputs
    = render partial: 'users/form', locals: { f: f, user: @user }

  .form-actions
    = f.button :submit, 'Update'

app/views/admin/users/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.
- `show_search_bar`:
  A boolean that determines if the search bar should be shown.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title" id="page-title">
    <%= content_for(:title) %>
  </h1>

  <% if show_search_bar %>
    <%= render(
      "search",
      search_term: search_term,
      resource_name: display_resource_name(page.resource_name)
    ) %>
  <% end %>

  <div>
    <%= link_to(
      "#{t("administrate.actions.new")} #{page.resource_name.titleize.downcase}",
      [:new, namespace, page.resource_path],
      class: "button",
    ) if valid_action? :new %>
  </div>
</header>

<section class="main-content__body main-content__body--flush">
  <%= render(
    "collection",
    collection_presenter: page,
    resources: resources,
    table_title: "page-title"
  ) %>

  <%= paginate resources %>
</section>

app/views/admin/users/index.html.slim
h1
  | Listing Users
table
  thead
    tr
      th First Name
      th Last Name
      th Email
      th Role
      th
      th
  tbody
    - @users.each do |user|
      tr
        td
          = user.first_name
        td
          = user.last_name
        td
          = link_to user.email, impersonate_admin_user_path(user)
        td
          = user.role_list
        td
          = link_to 'Edit', edit_admin_user_path(user)
        td
          = link_to_if(user != current_user, 'Destroy', admin_user_path(user), data: { confirm: 'Are you sure?' }, method: :delete)
br


= link_to 'New User', new_admin_user_path, class: 'btn'

app/views/admin/users/new.html.erb
<%#
# New

This view is the template for the "new resource" page.
It displays a header, and then renders the `_form` partial
to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) { "#{t("administrate.actions.new")} #{page.resource_name.titleize}" } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to t("administrate.actions.back"), :back, class: "button" %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

app/views/admin/users/new.html.slim
h2 Add User

= simple_form_for(@user, url: admin_users_path, html: { method: :post }) do |f|
  = errors_for(@user)
  .form-inputs
    = render partial: 'users/form', locals: { f: f, user: @user }
    br
    = label_tag 'admin', 'Admin?', style: 'float: left;'
    = check_box_tag 'admin', 'true', false, style: 'margin-left: 8px;'
    .clearfix
    = label_tag 'club_admin', 'Club Admin?', style: 'float: left;'
    = check_box_tag 'club_admin', 'true', false, style: 'margin-left: 8px;'
    .clearfix
    = label_tag 'coach', 'Coach?', style: 'float: left;'
    = check_box_tag 'coach', 'true', false, style: 'margin-left: 8px;'
    .clearfix
    = label_tag 'player', 'Player?', style: 'float: left;'
    = check_box_tag 'player', 'true', false, style: 'margin-left: 8px;'

  .clearfix
    br

  .form-actions
    = f.button :submit, 'Create'

app/views/admin/users/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { "#{t("administrate.actions.show")} #{page.page_title}" } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <% if page.resource.invitation_not_accepted? %>
      <%= button_to 'Invite', invite_admin_user_path(page.resource), method: :post, class: 'button', form_class: 'invite-coach-button', data: { confirm: 'Are you sure you want to send out an invite for this user?' } %>
    <% end %>

    <%= link_to(
      "#{t("administrate.actions.edit")} #{page.page_title}",
      [:edit, namespace, page.resource],
      class: "button",
    ) if valid_action? :edit %>
  </div>
</header>

<section class="main-content__body">
  <dl>
    <% page.attributes.each do |attribute| %>
      <dt class="attribute-label" id="<%= attribute.name %>">
      <%= t(
        "helpers.label.#{resource_name}.#{attribute.name}",
        default: attribute.name.titleize,
      ) %>
      </dt>

      <dd class="attribute-data attribute-data--<%=attribute.html_class%>"
          ><%= render_field attribute %></dd>
    <% end %>
  </dl>
</section>